services:
    _defaults:
        autowire: true

    Symfony\Component\Console\Application:
        public: true

# Symfony Command
    basic_block.command.create_board_command:
        public: true
        class: Aggrego\BasicBlockExample\Command\CreateBoardCommand
        tags: ['console.command']
        arguments:
            - '@messenger.bus'

    basic_block.command.transform_board_command:
        public: true
        class: Aggrego\BasicBlockExample\Command\TransformBoardCommand
        tags: ['console.command']
        arguments:
            - '@messenger.bus'

# Symfony Messenger
    messenger.bus:
        class: Symfony\Component\Messenger\MessageBus
        tags: ['messenger.bus']
        arguments:
          - ['@messenger.bus.middleware.handle_message']

    messenger.bus.middleware.handle_message:
        class: Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
        arguments:
            - [] # Filled by MessengerPass

    console.command.messenger_debug:
        public: true
        class: Symfony\Component\Messenger\Command\DebugCommand
        tags: ['console.command']
        arguments:
            - [] # Filled by MessengerPass

    messenger.bus.messenger.handlers_locator:
        class: Symfony\Component\Messenger\Handler\HandlersLocator
        tags: ['container.service_locator']
        arguments:
            - [] # Filled by MessengerPass

    domain_event_producer.handler.create_board:
        class: Aggrego\DomainEventProducer\Messenger\Handlers\CreateBoardHandler
        public: true
        tags: [{name: 'messenger.message_handler', handles: Aggrego\Domain\Api\Command\CreateBoard\Command, method: 'handle'}]
        arguments:
            - '@domain.api.create_board.use_case'
            - '@domain_event_producer.domain.repository'
            - '@aggrego.neo4j.event_consumer.client'

    domain_event_producer.handler.transform_board:
        class: Aggrego\DomainEventProducer\Messenger\Handlers\TransformBoardHandler
        public: true
        tags: [{name: 'messenger.message_handler', handles: Aggrego\Domain\Api\Command\TransformBoard\Command, method: 'handle'}]
        arguments:
            - '@domain.api.transform_board.use_case'
            - '@domain_event_producer.domain.repository'
            - '@aggrego.neo4j.event_consumer.client'

    domain_event_producer.domain.repository:
        class: Aggrego\DomainEventProducer\Domain\Repository
        arguments:
            - '@basic_block.board.repository'

# Domain Board
    domain.api.create_board.use_case:
        class: Aggrego\Domain\Api\Command\CreateBoard\UseCase
        arguments:
            - "@domain_event_producer.domain.repository"
            - "@domain.board.new_board_factory"

    domain.api.transform_board.use_case:
        class: Aggrego\Domain\Api\Command\TransformBoard\UseCase
        arguments:
            - "@domain_event_producer.domain.repository"
            - "@domain.board.from_board_factory"

    domain.board.new_board_factory:
        class: Aggrego\Domain\Board\NewBoardFactory
        arguments:
            - ['@domain.data_board.board.builder']
            - "@domain.profile.board_construction.factory"

    domain.board.from_board_factory:
        class: Aggrego\Domain\Board\FromBoardFactory
        arguments:
            - ['@domain.data_board.board.builder']
            - "@domain.profile.board_transformation.factory"

# Domain Profile
    domain.profile.board_construction.factory:
        class: Aggrego\Domain\Profile\BoardConstruction\Factory
        arguments:
            - ["@basic_block.domain.profile.board_construction.watchman"]

    domain.profile.board_transformation.factory:
        class: Aggrego\Domain\Profile\BoardTransformation\Factory
        arguments:
            - ["@basic_block.domain.profile.board_transformation.watchman"]

# Data Board
    domain.data_board.board.builder:
        class: Aggrego\DataBoard\Board\Builder

# BasicExample Profile
    basic_block.board.repository:
        class: Aggrego\BasicBlockExample\Domain\Board\Repository

    basic_block.domain.profile.board_construction.watchman:
        class: Aggrego\BasicBlockExample\Domain\Profile\BoardConstruction\Watchman

    basic_block.domain.profile.board_transformation.watchman:
        class: Aggrego\BasicBlockExample\Domain\Profile\BoardTransformation\Watchman

# Neo4j
    aggrego.neo4j.event_consumer.client:
        class: Aggrego\BasicBlockExample\EventConsumer\Neo4j\Client
        factory: ['@aggrego.neo4j.event_consumer.factory', factory]

    aggrego.neo4j.event_consumer.factory:
        class: Aggrego\BasicBlockExample\EventConsumer\Neo4j\Factory

