parameters:
    locale: 'en'

services:
    _defaults:
        autowire: false

    Symfony\Component\Console\Application:
        public: true

# Symfony Command
    basic_block_example.command.create_board_command:
        public: true
        class: Aggrego\BasicBlockExample\Command\CreateBoardCommand
        tags: ['console.command']
        arguments:
            - '@messenger.bus'

    basic_block_example.command.transform_board_command:
        public: true
        class: Aggrego\BasicBlockExample\Command\TransformBoardCommand
        tags: ['console.command']
        arguments:
            - '@messenger.bus'

# Symfony Messenger
    messenger.bus:
        class: Symfony\Component\Messenger\MessageBus
        tags: ['messenger.bus']
        arguments:
          - ['@messenger.bus.middleware.handle_message']

    messenger.bus.middleware.handle_message:
        class: Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
        arguments:
            - [] # Filled by MessengerPass

    console.command.messenger_debug:
        public: true
        class: Symfony\Component\Messenger\Command\DebugCommand
        tags: ['console.command']
        arguments:
            - [] # Filled by MessengerPass

    messenger.bus.messenger.handlers_locator:
        class: Symfony\Component\Messenger\Handler\HandlersLocator
        tags: ['container.service_locator']
        arguments:
            - [] # Filled by MessengerPass

    domain_event_producer.handler.create_board:
        class: Aggrego\DomainEventProducer\Messenger\Handlers\CreateBoardHandler
        public: true
        tags: [{name: 'messenger.message_handler', handles: Aggrego\Domain\Api\Command\CreateBoard\Command, method: 'handle', bus: 'messenger.bus'}]
        arguments:
            - '@domain.api.create_board.use_case'
            - '@domain_event_producer.domain.repository'
            - '@aggrego.command_logic_unit.event_consumer.client'

    domain_event_producer.handler.transform_board:
        class: Aggrego\DomainEventProducer\Messenger\Handlers\TransformBoardHandler
        public: true
        tags: [{name: 'messenger.message_handler', handles: Aggrego\Domain\Api\Command\TransformBoard\Command, method: 'handle', bus: 'messenger.bus'}]
        arguments:
            - '@domain.api.transform_board.use_case'
            - '@domain_event_producer.domain.repository'
            - '@aggrego.command_logic_unit.event_consumer.client'

    domain_event_producer.domain.repository:
        class: Aggrego\DomainEventProducer\Domain\Repository
        arguments:
            - '@basic_block_example.board.repository'

# Domain Board
    domain.api.create_board.use_case:
        class: Aggrego\Domain\Api\Command\CreateBoard\UseCase
        arguments:
            - "@domain_event_producer.domain.repository"
            - "@domain.board.new_board_factory"

    domain.api.transform_board.use_case:
        class: Aggrego\Domain\Api\Command\TransformBoard\UseCase
        arguments:
            - "@domain_event_producer.domain.repository"
            - "@domain.board.from_board_factory"

    domain.board.new_board_factory:
        class: Aggrego\Domain\Board\NewBoardFactory
        arguments:
            - ['@domain.data_board.board.builder']
            - "@domain.profile.board_construction.factory"

    domain.board.from_board_factory:
        class: Aggrego\Domain\Board\FromBoardFactory
        arguments:
            - ['@domain.data_board.board.builder']
            - "@domain.profile.board_transformation.factory"

# Domain Profile
    domain.profile.board_construction.factory:
        class: Aggrego\Domain\Profile\BoardConstruction\Factory
        arguments:
            - ["@basic_block_domain_profile.domain.profile.board_construction.watchman"]

    domain.profile.board_transformation.factory:
        class: Aggrego\Domain\Profile\BoardTransformation\Factory
        arguments:
            - ["@basic_block_domain_profile.domain.profile.board_transformation.watchman"]

# Data Board
    domain.data_board.board.builder:
        class: Aggrego\DataBoard\Board\Builder

# BasicExample Profile
    basic_block_example.board.repository:
        class: Aggrego\FileDomainRepository\Domain\Board\Repository

    basic_block_domain_profile.domain.profile.board_construction.watchman:
        class: Aggrego\BasicBlockDomainProfile\Domain\Profile\BoardConstruction\Watchman

    basic_block_domain_profile.domain.profile.board_transformation.watchman:
        class: Aggrego\BasicBlockDomainProfile\Domain\Profile\BoardTransformation\Watchman

# Neo4jIntegration
    aggrego.neo4j_integration.db_client.factory:
        class: Aggrego\Neo4jIntegration\Integration\DbClient\Factory

    aggrego.neo4j_integration.db_client.client:
        class: GraphAware\Neo4j\DbClient\Client
        factory: [ '@aggrego.neo4j_integration.db_client.factory', factory]
        arguments:
            - default: 'http://neo4j:aaaaaa@neo4j:7474'

    aggrego.neo4j_integration.api.run_command:
        class: Aggrego\Neo4jIntegration\Api\Command\RunCommand\UseCase
        public: true
        tags: [{name: 'messenger.message_handler', handles: Aggrego\Neo4jIntegration\Api\Command\RunCommand\Command, method: 'handle', bus: 'messenger.bus'}]
        arguments:
            - '@aggrego.neo4j_integration.db_client.client'

# CommandConsumer
    basic_block_example.command_consumer.message_bus_client:
        class: Aggrego\BasicBlockExample\CommandConsumer\MessageBusClient
        arguments:
            - '@messenger.bus'

# CommandLogicUnit
    aggrego.command_logic_unit.event_consumer.client:
        class: Aggrego\CommandLogicUnit\EventConsumer\Client
        arguments:
          - '@basic_block_example.command_logic_unit.event_processor.board.created_event'
          - '@basic_block_example.command_consumer.message_bus_client'
          - '@basic_block_example.command_logic_unit.response_processor.neo4j_integration.run_command.factory'
          - '@aggrego.event_consumer.blank_client'

    basic_block_example.command_logic_unit.event_processor.board.created_event:
        class: Aggrego\BasicBlockExample\CommandLogicUnit\EventProcessor\BoardCreatedEvent

    basic_block_example.command_logic_unit.response_processor.neo4j_integration.run_command.factory:
        class: Aggrego\BasicBlockExample\CommandLogicUnit\ResponseProcessor\Neo4jIntegration\RunCommandFactory

# Event Consumer
    aggrego.event_consumer.blank_client:
        class: Aggrego\BasicBlockExample\EventConsumer\BlackClient